### ISSUE TITLE
[Catalyst] Failed to build in Xcode 14: 'kIOMasterPortDefault' is unavailable in Mac Catalyst

### ISSUE THREAD

**Issue by gongzhang** [tikhop/TPInAppReceipt#102]
Hello, I found `TPInAppReceipt` failed to build with Xcode 14 beta 4 when targeted to Mac Catalyst. The error is as below.

<img width="739" alt="image" src="https://user-images.githubusercontent.com/4470629/181663113-5c077e8b-bd11-4226-b3d1-a4dfd780168f.png">

I tried modified the deprecated `kIOMasterPortDefault` to `kIOMainPortDefault` but it does not seem to work.

<img width="739" alt="image" src="https://user-images.githubusercontent.com/4470629/181663290-ad469ee2-3ab9-498b-8291-ba0a1f0ad609.png">

**Comment by tikhop** [comment]
Hi @gongzhang, I have just merged a related PR: https://github.com/tikhop/TPInAppReceipt/pull/101
Thanks for reminding me.

**Comment by gongzhang** [comment]
@tikhop You're so quick. Thanks!
