### ISSUE TITLE
Compiled module was created by an older version of the compiler

### ISSUE THREAD

**Issue by Jim3750** [tikhop/TPInAppReceipt#103]
Hi,
I have been using TPInAppReceipt in my app "Pilot Log for Tesla" (thank you). I have had no issue so far.
However in Xcode (latest) I now get "Compiled module was created by an older version of the compiler; rebuild 'TPInAppReceipt' and try again". This appears as a "red" error, but the build is successful and the app runs normally.
Not sure the matter is on your side, but, I'd appreciate your insight on this issue.
Thks

**Comment by Jim3750** [comment]
Well, it appears to be happening only when building for the simulator. The message does not show up when using a real device.
Thks

**Comment by tikhop** [comment]
@Jim3750 Might be some cache issue on your side, since the lib itself doesn't contain any pre-compiled binaries - just source code that you compile on your side.
