### ISSUE TITLE
Xcode 15 beta 3 - ld: warning: duplicate -rpath

### ISSUE THREAD

**Issue by gongzhang** [tikhop/TPInAppReceipt#110]
Hello,

Just notice that in Xcode 15 beta 3, the linker will output a group of warnings when build the package. The warnings are new in Xcode 15 beta 3, and not reproduce in beta 2 and 1.

## Steps to Reproduce

1. Clone the repo and checkout version 3.3.4
2. Open the local directory in Xcode 15 beta 3
3. Build the Swift Package target
4. The build will success but with linker warnings

<img width="1185" alt="image" src="https://github.com/tikhop/TPInAppReceipt/assets/4470629/feee5a84-ac0c-47b2-9f01-130d207bf973">

```
ld: warning: duplicate -rpath '/Users/gong/Library/Developer/Xcode/DerivedData/TPInAppReceipt-bhndaevgxhtrsbbnuvjnwglhjyck/Build/Products/Debug-iphonesimulator/PackageFrameworks' ignored
ld: warning: duplicate -rpath '@loader_path/Frameworks' ignored
ld: warning: could not associate debug note to atom l_OBJC_LABEL_PROTOCOL_$_SKRequestDelegate
ld: warning: could not associate debug note to atom l_OBJC_LABEL_PROTOCOL_$_NSObject
ld: warning: could not associate debug note to atom l_OBJC_PROTOCOL_REFERENCE_$_SKRequestDelegate
ld: warning: could not associate debug note to atom l_OBJC_PROTOCOL_REFERENCE_$_NSObject

Duplicate -rpath '/Users/gong/Library/Developer/Xcode/DerivedData/TPInAppReceipt-bhndaevgxhtrsbbnuvjnwglhjyck/Build/Products/Debug-iphonesimulator/PackageFrameworks' ignored
Duplicate -rpath '@loader_path/Frameworks' ignored
Could not associate debug note to atom l_OBJC_LABEL_PROTOCOL_$_SKRequestDelegate
Could not associate debug note to atom l_OBJC_LABEL_PROTOCOL_$_NSObject
Could not associate debug note to atom l_OBJC_PROTOCOL_REFERENCE_$_SKRequestDelegate
Could not associate debug note to atom l_OBJC_PROTOCOL_REFERENCE_$_NSObject
```

## Context

I suspect this may be a bug in the linker, not in the package. But I'm not familiar with compiler/link so could you confirm this? Thanks a lot! 😄

## Environment

* Version used: 3.3.4
* Xcode 15 beta 3
* macOS 13

**Comment by tikhop** [comment]
Hi @gongzhang, thanks for bringing this up. 

Unfortunately, I can't try xCode 15 for now, but I assume there is some issue with Xcode itself. 

Here is what I found in the wild (I think there is one from you): 
https://developer.apple.com/forums/thread/732099
https://developer.apple.com/forums/thread/733317
https://developer.apple.com/forums/thread/733280

Thank you!

**Comment by gongzhang** [comment]
@tikhop Thanks for the reply! You are right, it's a bug in Xcode 15 beta 3 because the warning reproduce in many packages. Feel free to close the issue :)
