### ISSUE TITLE
`originalAppVersion` returns build number on iOS and major and minor version number on macOS

### ISSUE THREAD

**Issue by DePasqualeOrg** [tikhop/TPInAppReceipt#114]
## Expected Behavior
The value should be consistent on both platforms.

## Steps to Reproduce (for bugs)
```swift
let receipt = try InAppReceipt.localReceipt()
let originalBuildVersion = receipt.originalAppVersion // Returns "28" on iOS and "1.28" in native macOS app
```

**Comment by tikhop** [comment]
Hello @DePasqualeOrg, thank you for bringing this up. Unfortunately, it's a feature, not a bug. 

[According to the documentation:](https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ReceiptFields.html)

> Original Application Version
> The version of the app that was originally purchased.
> 
> ASN.1 Field Type 19
> 
> ASN.1 Field Value UTF8STRING
> 
> JSON Field Name original_application_version
> 
> JSON Field Value string
> 
> This corresponds to the value of CFBundleVersion (in iOS) or CFBundleShortVersionString (in macOS) in the Info.plist file when the purchase was originally made.
> 
> In the sandbox environment, the value of this field is always “1.0”.

Please let me know if you have any further questions. Thank you!
