### ISSUE TITLE
TPInAppReceipt fails to build when building against visionOS SDK

### ISSUE THREAD

**Issue by jeffduet** [tikhop/TPInAppReceipt#117]
## Expected Behavior

When building against visionOS SDK, TPInAppReceipt should build without errors.

## Current Behavior

When building against visionOS SDK, there are several errors, including "Cannot find Bundle in scope" and "Cannot find type Data in scope' in Validation.swift.

## Steps to Reproduce (for bugs)

1. Use TPInAppReceipt in an app that is building for "Apple Vision" / "visionOS" as a supported destination.
2. Try to build project

## Context

Issue is preventing making a proper visionOS-SDK version of our app.

## Your Environment

* Version used:
* Environment name and version (device, simalator):
* Operating System and version (iOS, osx):
* Sonoma 14.3, Xcode 15.2
* Link to your project:

**Comment by tikhop** [comment]
Hi @jeffduet, thanks for bringing this up. There is a [PR](https://github.com/tikhop/TPInAppReceipt/pull/115) that addresses this issue. It has been merged, and I'm planning to release a new version ASAP.

Thank you!

**Comment by tikhop** [comment]
Hi @jeffduet, thanks for your patience. I have released a new version [3.4.0](https://github.com/tikhop/TPInAppReceipt/releases/tag/3.4.0). Thanks again for bringing this up!
