### ISSUE TITLE
Any support of Privacy Manifest?

### ISSUE THREAD

**Issue by iharkatkavets** [tikhop/TPInAppReceipt#120]
Privacy Updates for AppStore submission

## Expected Behavior
Developers are responsible for all code included in their apps. At WWDC23, Apple introduced new privacy manifests and signatures for commonly used third-party SDKs and announced that developers will need to declare approved reasons for using a set of APIs in their app’s privacy manifest.

## Current Behavior
The library doesn't provide Privacy Manifest file

## Possible Solution
The library should provide Privacy Manifest if it collects information or access "Required Reasons API"

## Additional Info

<img width="776" alt="image" src="https://github.com/tikhop/TPInAppReceipt/assets/1083951/0e38c55d-8ab6-4dfc-8597-c48bd11d9ea9">

**Comment by jigs4444** [comment]
I am also looking for same. Please add privacy manifest support

**Comment by tikhop** [comment]
@iharkatkavets @jigs4444 Thanks for bringing this up. I will add privacy manifest by the end of the week. If you want it faster, feel free to make a PR. Thank you!

**Comment by tikhop** [comment]
@iharkatkavets @jigs4444 Sorry for the delay. It has been released [here](https://github.com/tikhop/TPInAppReceipt/releases/tag/3.4.1). 

Thank you!
