### ISSUE TITLE
EXC_BAD_ACCESS on receiptData method

### ISSUE THREAD

**Issue by NameX44** [tikhop/TPInAppReceipt#14]
Hi,

I've got a problem recently on InAppReceiptManager : 

`
        guard let receiptUrl = Bundle.main.appStoreReceiptURL,
            FileManager.default.fileExists(atPath: receiptUrl.path) else
        {
            throw IARError.initializationFailed(reason: .appStoreReceiptNotFound)
        }
`

this guard let give me an EXC_BAD_ACCESS and i don't understand why. So I've got this exception from your lib : IARError.initializationFailed(reason: .appStoreReceiptNotFound). 

Lost many subscription due to that. Help me pls.

Thanks for your work btw !

**Comment by tikhop** [comment]
Hi,

I'll check it out in a few hours.

Thank you.

**Comment by tikhop** [comment]
@NameX44 Hi, I tried to reproduce your issue and I couldn't. 

Let me know if you are still facing this issue, maybe you can provide me your receipt (Data object).

Thank you.
