### ISSUE TITLE
EXEC_BAD_ACCESS in subscriptionExpirationDate

### ISSUE THREAD

**Issue by rpitting** [tikhop/TPInAppReceipt#15]
I just got an`fatal error: unexpectedly found nil while unwrapping an Optional value` for this code:

```swift
    public var subscriptionExpirationDate: Date
    {
        assert(isRenewableSubscription, "\(productIdentifier) is not an auto-renewable subscription.")
        
        return subscriptionExpirationDateString!.rfc3339date()
    }
```

This is caused by accessing an `InAppPurchase` an expired subscription (date-string is empty).

**Comment by tikhop** [comment]
@rpitting Just pushed a new version with a fix. 

Thank you.
