### ISSUE TITLE
Support for macOS 10.12

### ISSUE THREAD

**Issue by joaocolaco** [tikhop/TPInAppReceipt#16]
Hi
Thanks for the new release.

As a suggestion, can you make the Deployment Target in the macOS target 10.12 and not 10.13. I don't see any issue in supporting that version.

**Comment by tikhop** [comment]
Hi,

Yeah, I agree. Will do it tomorrow. 

Thanks.

**Comment by diederikh** [comment]
@tikhop Any outlook on when there will be a new release with a 10.12 target?

Thanks

**Comment by tikhop** [comment]
I'm sorry, It took longer than I expected.
