### ISSUE TITLE
openssl as a module file not correct

### ISSUE THREAD

**Issue by ovdm** [tikhop/TPInAppReceipt#17]
If I include TPInAppReceipt in my main file, the main file works fine. However if I compile my Test target, Swift will now try to include and compile openssl for the Test target and I get the error 
"...Pods/TPInAppReceipt/Vendor/OpenSSL/include/openssl/bio.h:62:11: 'openssl/e_os2.h' file not found" for all the swift files in my Test target.

My suspicion is that the Pods/TPInAppRceipt/Vendor/OpenSSL/module.modulemap has an error, but I don't know enough about modulemaps. IBM has created a module for Swift for OpenSSL. https://github.com/IBM-Swift/OpenSSL  Perhaps that is useable

**Comment by b-onc** [comment]
Having the same issue and is driving me crazy.

**Comment by svatrous** [comment]
Same issue

**Comment by b-onc** [comment]
@tikhop Can you prioritize this, please?

**Comment by tikhop** [comment]
@b-onc Yes. I've just had a chance to try it on osx and I'm able to reproduce it. I haven't tried to use it via pod tho. 

fyi - I've been working on improving the library and I'm trying to substitute openssl functionality with a custom solution. Currently, parsing a receipt works well without openssl. 

If you use the library only to parse (not validate) in-app receipt. I can break the lib on two (parsing, validating) where parsing part will be without openssl. (just a quick solution)

**Comment by b-onc** [comment]
@tikhop I see that you have an `openssl` branch, I've tried that and it solved our problems (our issues are not the same as described in this issue). Can we use keep using that branch?

As per your question, yes we're only using TPInAppReceipt for parsing the receipt, not validating. Splitting the pod into two smaller pods would work for our use case.

**Comment by tikhop** [comment]
@b-onc Ha, magic. I don't think I have fixed anything there.

I've pushed `develop` branch and all parsing there is happening w/o openssl. I will do some testing and release it within this week.

P

**Comment by tikhop** [comment]
New version with a fix has been released
