### ISSUE TITLE
Check free trial

### ISSUE THREAD

**Issue by NameX44** [tikhop/TPInAppReceipt#18]
Hi,

I don’t find a way to check if free trial on a auto renew subscription has been done or is in progress.

Could we add is_trial_period var in receipt ?

Thanks

**Comment by tikhop** [comment]
Hi,

Based on apple's docs. There is no way to have this property while parsing receipt locally.

```
Subscription Trial Period
For a subscription, whether or not it is in the free trial period.

ASN.1 Field Type (none)

ASN.1 Field Value (none)

JSON Field Name is_trial_period

JSON Field Value string

This key is only present for auto-renewable subscription receipts. The value for this key is "true" if the customer’s subscription is currently in the free trial period, or "false" if not.

Note: If a previous subscription period in the receipt has the value “true” for either the is_trial_period or the is_in_intro_offer_period key, the user is not eligible for a free trial or introductory price within that subscription group.


```

**Comment by b-onc** [comment]
Hello @tikhop 

Is it still the case that we can't parse the receipt locally and check if the user is eligible for a free trial?

**Comment by tikhop** [comment]
Hello @b-onc 

Unfortunately, we can't check whether the user is eligible for a free trial.
