### ISSUE TITLE
how to use this in objective c 

### ISSUE THREAD

**Issue by shaktiprakash099** [tikhop/TPInAppReceipt#21]

**Comment by tikhop** [comment]
@shaktiprakash099 Still a problem?

**Comment by dongmai** [comment]
Hi @tikhop ,

I've installed TPInAppReceipt via cocoapods for my objective C project and #import "TPInAppReceipt-Swift.h" on my header files but it still can't find InAppReceipt class.

Can you please give me some hints to use on objective C project?  
thanks

**Comment by tikhop** [comment]
@dongmai I will double check later today. Thanks for your feedback.

**Comment by tikhop** [comment]
@dongmai Just double checked and it really doesn't work in objc project. In order to make it work I have to change only a few lines, but it will bring back NSObject and the whole objc world back into the swift project. 

I can create a separate branch, theoretically, with a code which will work in objc, but I'm not sure that I will maintain it.

Best,
P

**Comment by dongmai** [comment]
@tikhop thanks for your info, you dont have to create a branch for that :-)

**Comment by tikhop** [comment]
@dongmai you are welcome. Let me know if you have any questions.

**Comment by monish152** [comment]
Is it working for objective c?

**Comment by tikhop** [comment]
Hi @monish152,

I'm sorry, unfortunately, it doesn't work inside objc project

**Comment by tikhop** [comment]
https://github.com/tikhop/TPInAppReceipt/issues/84#issuecomment-817739621

**Comment by tikhop** [comment]
Hi @shaktiprakash099, @monish152 

I’ve created an example of using the library inside objc project.

https://gist.github.com/tikhop/7d1215bbcea7fe8a3be3ce5ef25e15ee

**Comment by tikhop** [comment]
Hi @shaktiprakash099, @monish152 

Just released a new version [3.2.0](https://github.com/tikhop/TPInAppReceipt/releases/tag/3.2.0) and now it works in objc projects. 

If you are using cocoapods just do:

```
pod 'TPInAppReceipt/Objc'
```

Let me know if you have any questions.
