### ISSUE TITLE
How to test during debugging?

### ISSUE THREAD

**Issue by georgbachmann** [tikhop/TPInAppReceipt#22]
Stupid question... but do you have any idea how I can debug while testing?
What I'd need to figure out is the original version the user has ever installed of my app. So there's the `receipt.originalAppVersion` property. But how can I test that when I am debugging my app? Cause with Xcode attached, the receipt from the App Store is gone, right?

**Comment by tikhop** [comment]
@georgbachmann I don't think I understand your question. If you want to debug you can put a breakpoint inside your app (in xCode) wherever you want, even inside this library, and investigate anything you'd like to: variable, raw memory value, etc...

**Comment by georgbachmann** [comment]
The question was about how you can test receipt validation, as there is no real receipt during testing in sandbox. At least the `originalAppVersion` will alway be a dummy one... But never mind. I already tested it enough.. (issue is quite old anyway...)
