### ISSUE TITLE
Swift 5 support?

### ISSUE THREAD

**Issue by neilt** [tikhop/TPInAppReceipt#23]
Is there any plan for an update to remove the public modifier warnings shown in Xcode 10.2.1?

**Comment by tikhop** [comment]
@neilt I can try to do it quickly during the week

**Comment by neilt** [comment]
No problem, it is not a show stopper, but I had not seen any update in a while was just wondering.

**Comment by tikhop** [comment]
@neilt Hello, sorry for a delay, I've been working on removing openssl and substituting it with own parser. I will push it today as a new release. Migration on Swift 5 will be included.

**Comment by tikhop** [comment]
New version with swift 5+ support has been released

**Comment by neilt** [comment]
Thanks.
