### ISSUE TITLE
Prepare for UIKitForMacOS

### ISSUE THREAD

**Issue by chnbr** [tikhop/TPInAppReceipt#24]
If I use the project with  the new "Mac"-target provided in Xcode-11-beta I get the following error:

**ld: in ...../Pods/TPInAppReceipt/Vendor/OpenSSL/iOS/libcrypto.a(tasn_typ.o), building for UIKitForMac, but linking in object file built for iOS Simulator, for architecture x86_64**

Clearly this comes from the pre-compiled SSL libraries which are shipped as binary. How can we integrate the SSL libraries compiled for the "Mac"-target ?  I assume that they are already there, provided from the system, but I don't know how specify this in the pod or at Xcode linker level.

Any recommendations or - even better - solutions to this ?

Thanks

**Comment by chrisvanbuskirk** [comment]
I believe it will need an xcframework.  A thread to read below.

https://forums.developer.apple.com/thread/117229

**Comment by tikhop** [comment]
@chnbr Hello, thank you for posting your issue. I'm currently working on removing openssl from the project and, if you check `develop` branch, you will notice that openssl is being used only for certificate validation. I'm planning to roll out a new release within this week which will work w/o linking openssl (only if you need parsing a basic validation). There will be another pod with openssl included as a cocoapod dependency just for validation (in future I will validate w/o openssl as well)

P

**Comment by tikhop** [comment]
Just released a new version without using OpenSSL.

**Comment by tikhop** [comment]
@chnbr I assume that the issue has been fixed. Let me know if you have any problems...

**Comment by chnbr** [comment]
Thank you very much for your work, much appreciated. The complier can't find InAppReceipt.localReceipt().verify() anymore. Is this the function that is temporarily disabled or did you rename it to verifyHash() ?

**Comment by tikhop** [comment]
@chnbr It's been removed, since the current (cocoapod) version only verifies receipt's hash. Last developer version (master branch) contains additional verification processes. I will bring that function back in the next release.

**Comment by tikhop** [comment]
@chnbr FYI, `InAppReceipt.localReceipt().verify()' is available again in the last dev version (master branch)

If you use it thru cocoapods you just need `pod 'TPInAppReceipt', :git => 'https://github.com/tikhop/TPInAppReceipt.git', :branch => :master`
