### ISSUE TITLE
Value of type 'UnsafePointer<_>' has no member 'baseAddress'  in Data+Extension.Swift

### ISSUE THREAD

**Issue by gnaseri** [tikhop/TPInAppReceipt#25]
Hello,

Thanks for the TPInAppReceipt pod.

I was  TPInAppReceipt in my project for local receipt validation and it was working fine till today that I updated pods. After updating, I get a "Value of type 'UnsafePointer<_>' has no member 'baseAddress'"  error in Data+Extension.Swift file:

```
public extension Data
{
    @inlinable var pointee: UnsafeRawPointer
    {
        let p: UnsafeRawPointer = self.withUnsafeBytes { rawBufferPointer in
            return rawBufferPointer.baseAddress!   // Error comes here :"Value of type 'UnsafePointer<_>' has no member 'baseAddress'"
        }
        
        return p
    }
}
```

Any help or solutions would be appreciated.
I am using Swift 4.2.

Thanks.

**Comment by tikhop** [comment]
@gnaseri Are you using it for iOS or OSX? Can you try to compile it with swift 5.0 (I think you can select swift version only for this pod). 

P

**Comment by gnaseri** [comment]
tikhop Thanks for your reply. 

It's for ios. I don't have Swift 5 in "Build Settings" of my project to be able to compile my project with Swift 5.0. I have not migrated to swift 5 yet (because migrating to Swift 5 may cause lots of delay in publishing my app since it first needs upgrading Xcode from 10.1 to 10.2 and therefore, upgrading my Laptop's OS, and it may also causes errors in many other pods that I'm implementing in my project. So, I would prefer to publish my current project in swift 4.2 if possible.) 
If possible, would you consider changing the code to be also compilable by swift 4.2 as it was before the last release? (if you think it would be useful for other TPInAppReceipt users of course)

Thanks.

**Comment by tikhop** [comment]
@gnaseri I hear you! Actually, I've tried to compile the project with swift 4.2 and it's working well. I will try to do the same for iOS project and using cocoapods.

**Comment by tikhop** [comment]
@gnaseri Just tried to create new iOS project add `TPInAppReceipt` as a pod, changed swift version everywhere to 4.2 and it's working. Which iOS SDK are you using?

**Comment by tikhop** [comment]
@gnaseri Could you please try to instal the pod using this line:

`pod 'TPInAppReceipt', :git => 'https://github.com/tikhop/TPInAppReceipt.git', :branch => :master`

it will use the last code from master brunch which doesn't include that problematic piece of code. 

P

**Comment by gnaseri** [comment]
Thank you vary much for your prompt reply and suggestion. After installing the pod using your line of code and also doing the following change in "ASN1Object+Sequence.swift"  it compiled successfully, but has after opening the app for the second time, it has the "Unexpectedly found nil while unwrapping an Optional value" error for "let payload = ASN1Object(data: asn1Data)"  code in "InAppReceiptPayload.swift".  Here is what happened in detail:

1- I deleted the pod and re-installed it by using the line you mentioned:
`pod 'TPInAppReceipt', :git => 'https://github.com/tikhop/TPInAppReceipt.git', :branch => :master`

2- Then, like yesterday that I had updated the pod, I got the “Use of local variable 'asn1' before its declaration” error in ASN1Object+Sequence.swift:
`//Use of local variable 'asn1' before its declaration`

So, I changed the code from 

```
mutating func next() -> Element?
    {
        guard bytes.count > 0, asn1.identifier.encodingType == .constructed, bytesLeft > 0 else   //Use of local variable 'asn1' before its declaration
        {
            return nil
        }
        
        let valueData = Data(bytes[offset..<bytes.count])
        let asn1 = ASN1Object(data: valueData)
        lastItem = asn1
        
        bytesLeft -= asn1.bytesCount
        offset += asn1.bytesCount
        
        return asn1
    }
```

to

```
  mutating func next() -> Element?
    {
        let valueData = Data(bytes[offset..<bytes.count])
        let asn1 = ASN1Object(data: valueData)
        
        guard bytes.count > 0, asn1.identifier.encodingType == .constructed, bytesLeft > 0 else
        {
            return nil
        }
        
        
        lastItem = asn1
        
        bytesLeft -= asn1.bytesCount
        offset += asn1.bytesCount
        
        return asn1
    }

```
3- Then, my project compiled successfully. So, I purchased the app in test device to have the receipt locally ( The local receipt verification used to work fine after purchasing). After re-opening the app to test the verification of local receipt, the app crashed and I got the following error in InAppReceiptPayload.swift:

```
let payload = ASN1Object(data: asn1Data)  // Error: Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value
        payload.enumerateInAppReceiptAttributes { (attribute) in
            if let field = InAppReceiptField(rawValue: attribute.type)
            {

```

Does it have anything to do with how I get the receipt: `let receipt = try InAppReceipt.localReceipt()`
vs. `// let receipt = try InAppReceiptManager.shared.receipt()`, or with `//Import openssl `? (I could not import it again after re-installing the pod using the line of code you provided since I’m getting  `No such module 'openssl’` error since yesterday that I first updated the pod.)

My  iOS SDK  is Xcode Version 10.1 (10B61)

Thanks.

**Comment by tikhop** [comment]
@gnaseri You can stick with an old version of the lib, if you are using cocoapods just install an old version < 2.0.0
