### ISSUE TITLE
Validation issue

### ISSUE THREAD

**Issue by chrisvanbuskirk** [tikhop/TPInAppReceipt#28]
`        #if os(iOS) || os(watchOS) || os(tvOS)
        guard let v = Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String,
            v == originalAppVersion else
        {
            throw IARError.validationFailed(reason: .bundleVersionVefirication)
        }
`

Should be CFBundleVersion and compared to appVersion not originalAppVersion.

**Comment by tikhop** [comment]
@chrisvanbuskirk thank you.

Fixed.

**Comment by chrisvanbuskirk** [comment]
Thanks for fixing...however, you might want to address the Mac side, which I believe is CFBundleShortVersionString instead.  Also, might be appVersion not originalAppVersion.

**Comment by tikhop** [comment]
@chrisvanbuskirk thanks again. Just made a fix, pushing in a bit.
