### ISSUE TITLE
appleIncRootCertificateNotFound

### ISSUE THREAD

**Issue by truemetal** [tikhop/TPInAppReceipt#3]
Hi, I get this issue if install via cocoapods as described

```
2017-02-03 13:52:56.618413 test-validate[2488:578098] appStoreReceiptURL: file:///private/var/mobile/Containers/Data/Application/505D79D0-6DA5-4D8E-8473-1B04AF9D0E31/StoreKit/sandboxReceipt
appleIncRootCertificateNotFound
```
It goes away, though, if I manually copy `AppleIncRootCertificate.cer` to my project and include it to my target 

Thanks

**Comment by tikhop** [comment]
Hi, thanks for letting me know. I will take a look shortly.

**Comment by tikhop** [comment]
@truemetal Hey, I couldn't reproduce the issue. I've made a fresh project, installed the pod and I can see that certificate inside the framework's bundle. 

Cocoapod 1.1.1

What's your version of cocoapod?

**Comment by truemetal** [comment]
@tikhop the described error happens in runtime, when I try to execute this line: 
`let receipt = try InAppReceiptManager.shared.receipt()` 

yes, my cocoapods version is 1.1.1

**Comment by tikhop** [comment]
@truemetal Yeah, I'm also testing in runtime. Moreover, this error can't happen when you execute that line. It seems that you have an old version of the library, because I throw this error only if you try to validate the receipt.

**Comment by truemetal** [comment]
@tikhop you're right, I've had outdated pod version. This podfile: 
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test-pod' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for test-pod
  pod 'TPInAppReceipt'
end
```

Produced this `Podfile.lock`:
```
PODS:
  - TPInAppReceipt (0.0.7.3)

DEPENDENCIES:
  - TPInAppReceipt

SPEC CHECKSUMS:
  TPInAppReceipt: 256bd4659cd93f9d16644db3d2b6a89c9089c14e

PODFILE CHECKSUM: c945987080b71e044ef877cb438dd756ef39e539

COCOAPODS: 1.1.1
```

After `pod update` everything is fine. Thank you.

**Comment by tikhop** [comment]
Cool.

Make sure that verification process used to be a part of initialization process. However, since version 1.0 you have to execute this line `try receipt.verify()` in order to validate the receipt.
