### ISSUE TITLE
Hash verification failing in 2.2.1

### ISSUE THREAD

**Issue by chrisvanbuskirk** [tikhop/TPInAppReceipt#30]
FYI...verifyHash is now failing in 2.2.1

**Comment by chrisvanbuskirk** [comment]
What I mean by failing is that the receipt hash is not equaling the generated hash.  It worked in 2.1.2...now not.

**Comment by tikhop** [comment]
@chrisvanbuskirk thanks for letting me know. Just pushed a fix.
