### ISSUE TITLE
 isRenewableSubscription always return true?

### ISSUE THREAD

**Issue by CheslauBachko** [tikhop/TPInAppReceipt#31]
ASN1-reader

`
@inlinable
    static func readString(from data: inout Data, _ l: Int, encoding: String.Encoding) -> String
    {
        return String(data: data, encoding: encoding) ?? ""
    }
`

parse

`
           case .subscriptionExpirationDate:
                    subscriptionExpirationDateString = ASN1.readString(from: &value, encoding: .ascii)
`

InAppPurchase

`
 var isRenewableSubscription: Bool
    {
        return self.subscriptionExpirationDateString != nil
    }
`

ASN1.readString no return nil value so isRenewableSubscription always return true?

**Comment by tikhop** [comment]
Hello @CheslauBachko, thanks for reporting this. I will push a fix in a bit.

**Comment by tikhop** [comment]
Hello @CheslauBachko, 

Just pushed an update which contains the fix. 

Thanks again.
