### ISSUE TITLE
Non consumable purchase

### ISSUE THREAD

**Issue by i-arun-samui** [tikhop/TPInAppReceipt#34]
First thanks for your approached with this library since we can get rid of openssl which is a real headache.

Since your library is focused on subscriptions, what about checking Non consumable purchase :
if the purchase hasn't been canceled CancelationDateString = nil right?
if the purchase has been canceled CancelationDateString != nil right?

thanks

**Comment by tikhop** [comment]
@i-arun-samui Thank you. You are welcome.

I assume you are right, better to check apple docs tho. I haven't worked with non consumable purchase yet and I can't test. It would be great If you have a chance to try it out and share your results here. 

Thanks,
P

**Comment by i-arun-samui** [comment]
Hi,
According to Apple docs if cancellation date exists it means purchase has been cancelled, otherwise it’s nil

It’s not possible to test this since tester can not cancel purchase.

Laurent
