### ISSUE TITLE
Hash Validation doesn't work

### ISSUE THREAD

**Issue by tosbaha** [tikhop/TPInAppReceipt#35]
I checked with my receipts, your receipt in Test Suite and validation is giving me an error.

**Comment by tikhop** [comment]
@tosbaha It's hard to say why it doesn't work for you and how did you test it. Please, provide more information in order to reproduce the issue.

**Comment by tosbaha** [comment]
I checked out the library with Xcode 11 SPM.(It checked out 2.2.3) Then opened my test suite and pasted your first test. It failed with 

> Test Suite 'Selected tests' started at 2019-10-16 17:33:30.923
> Test Suite 'ReceiptValidatorTests.xctest' started at 2019-10-16 17:33:30.923
> Test Suite 'ReceiptValidatorTests' started at 2019-10-16 17:33:30.923
> Test Case '-[ReceiptValidatorTests.ReceiptValidatorTests testExample]' started.
> Fatal error: 'try!' expression unexpectedly raised an error: TPInAppReceipt.IARError.validationFailed(reason: TPInAppReceipt.IARError.ValidationFailureReason.hashValidation): file /Users/mustafa/Desktop/ReceiptValidator/ReceiptValidatorTests/ReceiptValidatorTests.swift, line 27
> 2019-10-16 17:33:31.076795+0300 ReceiptValidator[36450:2558561] Fatal error: 'try!' expression unexpectedly raised an error: TPInAppReceipt.IARError.validationFailed(reason: TPInAppReceipt.IARError.ValidationFailureReason.hashValidation): file /Users/mustafa/Desktop/ReceiptValidator/ReceiptValidatorTests/ReceiptValidatorTests.swift, line 27

**Comment by tosbaha** [comment]
I am testing on macOS. I run your test suite on a iMac which is running on macOS Catalina. My use case is to test receipts that I have from users for its authenticity. I guess `hashValidation` is using the value from the device (`UIDevice.current.identifierForVendor!.uuid`) when this receipt is generated. So hashValidation can't be used to verify the receipt offline.

**Comment by tikhop** [comment]
@tosbaha Yes, you are right. GUID is being used when the receipt is generated. In order to test it on simulator (if you are using receipt from ios device) you have to hardcode guid of that device. It works offline, but you have to do it on you real device.
