### ISSUE TITLE
Can I make a port of this library to Objective-C?

### ISSUE THREAD

**Issue by cupnoodle** [tikhop/TPInAppReceipt#36]
Hi Pavel!

Sorry for using this issue, but I can't find a way to communicate (tikhop.com is down) with you.

I am interested on making an Objective-C version of this library, is this alright with you? I will be sure to credit you and link to this library file on the new library README file.

**Comment by tikhop** [comment]
Hi @cupnoodle.

Yeah, it's totally fine with me, but before doing that I would rather check existing solution written in ObjC.

Best,
P
