### ISSUE TITLE
[Catalyst] verifyHash fails

### ISSUE THREAD

**Issue by chrisvanbuskirk** [tikhop/TPInAppReceipt#38]
I have been testing TPInAppReceipt on the Mac/Catalyst, and verifyHash fails.

**Comment by tikhop** [comment]
@chrisvanbuskirk thanks for reporting. I will take a look.

**Comment by chrisvanbuskirk** [comment]
@tikhop Hi, any updates on this?  Kinda of holding up some releases and I don't really want to head back to OpenSSL.

**Comment by tikhop** [comment]
@chrisvanbuskirk Sorry to hear that. Unfortunately, i didn't have time to work on it and I'm not sure that it will be fixed shortly.

**Comment by chrisvanbuskirk** [comment]
@tikhop  I understand.  I did revert back to using OpenSSL, as it now can compile for Catalyst.  However, the method I use to verify the receipt hash v. the computed hash fails as well.  It works flawlessly on iOS.   I created a radar on the matter and now going through your code as well, which I might include in the radar.  I now think something is up with the receipt.  I wonder if they even tested it.  FB7470452

**Comment by chrisvanbuskirk** [comment]
@tikhop Looks like I was wrong.  There's some rules for catalyst like Mac

On the Mac you need to use the machine's mac address instead of the identifierForVendor as you do on iPhone/iPad. Take a look at:
     https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateLocally.html#//apple_ref/doc/uid/TP40010573-CH1-SW10
 
You can use the "copy_mac_address()" code on this page to replace the identifierForVendor when building up the expectedHash in the macCatalyst case.  I think you might have some code that resemblers this already.

Also, you need to use CFBundleShortVersionString instead of CFBundleVersion for catalyst.

**Comment by tikhop** [comment]
@chrisvanbuskirk thanks for additional information. I'm planning to take a look tomorrow.

**Comment by chrisvanbuskirk** [comment]
@tikhop Ok, I will wait a bit.

Be advised.  Catalyst apps report themselves as iOS.  You have to use:

// swift
#if targetEnvironment(macCatalyst)
...
//objc
#if TARGET_OS_UIKITFORMAC

Here's how I did my hash....it's all in obj-c
- (BOOL)verifyReceiptHash
{
    NSMutableData *data = [NSMutableData data];
    #if !TARGET_OS_UIKITFORMAC
    NSUUID *uuid = [UIDevice currentDevice].identifierForVendor;
    unsigned char uuidBytes[16];
    [uuid getUUIDBytes:uuidBytes];
    [data appendBytes:uuidBytes length:sizeof(uuidBytes)];
    #else
    [data appendData:(__bridge NSData * _Nonnull)(copy_mac_address())]; // It's a Mac catalyst app
    #endif
    [data appendData:self.opaqueValue];
    [data appendData:self.bundleIdentifierData];
    NSMutableData *expectedHash = [NSMutableData dataWithLength:SHA_DIGEST_LENGTH];
    SHA1((const uint8_t*)data.bytes, data.length, (uint8_t*)expectedHash.mutableBytes);
    
    return [expectedHash isEqualToData:self.receiptHash];
}

and bundled version

- (NSString*)bundleVersion
{
    if (!_bundleVersion)
    {
#if TARGET_OS_IPHONE
        #if !TARGET_OS_UIKITFORMAC
        return [[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleVersion"];
        #else
        return [[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleShortVersionString"];

        #endif
#else // Mac
        return [[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleShortVersionString"];
#endif
    }
    return _bundleVersion;
}

best...

**Comment by tikhop** [comment]
@chrisvanbuskirk Sweet, thanks for providing a code snippet.

**Comment by tikhop** [comment]
@chrisvanbuskirk Just released a new version. Thanks again for your help. 

Best,
P
