### ISSUE TITLE
Add support for non ASN.1 Fields

### ISSUE THREAD

**Issue by Zasuk** [tikhop/TPInAppReceipt#39]
Hi,
is it possible to add support for fields that can only be retrieved using JSON Field Name? for me the most important one is **is_trial_period** because we need to check this field and **is_in_intro_offer_period** together 

also a method to get a Dictionary representation of the receipt is really useful.

thanks for the awesome work!

**Comment by tikhop** [comment]
Hi @Zasuk,

Regarding the first issue. As I understand, you are fetching in-app receipt from apple server and you want to parse it using 'TPInAppReceipt`library? 

I agree, about having a method to get a dict representation if the receipt. I will implement during this week.

Thanks,
P

**Comment by Zasuk** [comment]
yes, i'm using `SKReceiptRefreshRequest` and then using this lib to parse and validate it (from local storage)

**Comment by Zasuk** [comment]
just to give more context i'm referring to "Determine Eligibility" [here](https://developer.apple.com/documentation/storekit/in-app_purchase/implementing_introductory_offers_in_your_app)

I did a quick check in source code and it looks like [some fields](https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ReceiptFields.html) are not parsed because they only have the json identifier

**Comment by tikhop** [comment]
Unfortunately, we can't retrieve these (JSON) fields from a local receipt.

**Comment by tikhop** [comment]
I would recommend to check JSON fields on your server and handle all business logic which is related to those fields on backend.

Best,
P
