### ISSUE TITLE
Import IOKit won't compile on macOS

### ISSUE THREAD

**Issue by CineDev** [tikhop/TPInAppReceipt#45]
### Platform

- [ ] macOS

### Environment

- [ ] Sandbox
- [ ] Production

### Version

current
## Report

Import IOKit is a wrong line, resulting in non-compliled code

### Issue summary
for macOS target you importing IOKit, but you should import Cocoa. Now the code won't compile

### What did you expect to happen
ℹ Please replace this with what you expected to happen.

### What happened instead
ℹ Please replace this with what happened instead.

**Comment by tikhop** [comment]
@CineDev Thanks for reporting. I will take a look. Are you trying to build mac catalyst project or just a regular macOS app?

Thanks,
P

**Comment by CineDev** [comment]
Regular. But IOKit isn't applicable here anyway. It's using for hardware and drivers access only. You need Cocoa framework instead.

**Comment by CineDev** [comment]
Let me show you what's happening when I'm linking your code [https://drive.google.com/open?id=1TlgFEvJymVcIxxdsnVZ8A7h4qsOEZaAi](url)

**Comment by CineDev** [comment]
Now code compiles. Thanks!

**Comment by tikhop** [comment]
Great! Thanks again for reporting. 

Best,
P
