### ISSUE TITLE
localReceipt not creating local receipt file in the sandbox environment

### ISSUE THREAD

**Issue by CineDev** [tikhop/TPInAppReceipt#46]
### Platform

- [ ] macOS

### Environment

- [ ] Sandbox

### Version
ℹ 2.2

### Related issues
ℹ Please replace this with references to similar issues (either open or already closed).

### Issue summary
ℹ localReceipt call results in error with code 0 on sandbox environment,

### What did you expect to happen
ℹ I expect the mac app store login window where I can type my test user login info

### What happened instead
ℹ Please replace this with what happened instead.

**Comment by tikhop** [comment]
@CineDev This library can be used only for validating and parsing local receipt. If you don't have a receipt you should refresh local receipt using StoreKit. 

Refreshing receipt will be available in the next release. 

Best,
P

**Comment by CineDev** [comment]
Thanks for reply. Didn't understand than: what's the point of localReceipt var?

**Comment by tikhop** [comment]
`localReceipt` returns the receipt from your device. There is a case when the local receipt isn’t available, therefore you have to refresh it first and then you can try to retrieve again.
