### ISSUE TITLE
Permanent ValidationFailed error

### ISSUE THREAD

**Issue by CineDev** [tikhop/TPInAppReceipt#47]
### Platform

- [ ] macOS

### Environment

- [ ] Sandbox
- [ ] Production

### Version
ℹ 2.3.4

### Issue summary
ℹI get permanent ValidationFailed error. Rolled back to version 2.2 and everything works fine

### What did you expect to happen
ℹ expect the validation will be success on apple's MAS receipt

### What happened instead
ℹ Please replace this with what happened instead.

**Comment by tikhop** [comment]
@CineDev could you please provide a failure reason.

**Comment by CineDev** [comment]
error.localizedDescription contains error code 1. That's all

**Comment by tikhop** [comment]
there should be a reason `ValidationFailureReason` then I can understand at which stage of validation you get a failure

**Comment by CineDev** [comment]
I'll try to play around tonight. We'll provide you information as much as I can

**Comment by tikhop** [comment]
@CineDev Thank you!

**Comment by tikhop** [comment]
@CineDev you can get a reason by doing next:

```
do {
        try receipt.verify()
} catch IARError.validationFailed(let reason)
{
        print(reason)
}
```

Best,
P

**Comment by CineDev** [comment]
signatureValidation(TPInAppReceipt.IARError.SignatureValidationFailureReason.appleIncRootCertificateNotFound)

**Comment by tikhop** [comment]
@CineDev well, from the README

Note: Currenty, SwiftPM doesn't support the feature of adding resources to package and therefore you have to add the Apple Root Certificate manually. You can find it here.

You need to download Apple Inc Root Cert.

Best,
P
