### ISSUE TITLE
Binary rejected from Mac App Store

### ISSUE THREAD

**Issue by CineDev** [tikhop/TPInAppReceipt#48]
### Platform

- [x] macOS

### Environment

- [x] Production

### Version
2.3.4

### Issue summary
Submitting binary with v2.3 of the framework went well. Binary was accepted. But when I updated the framework to v2.3.4, my binary was rejected by Apple's review team with this message:

'We noticed that with a valid receipt installed, your app quits on launch. The Console reports the app "Exited with exit code: 173" and the OS states the app "is damaged and can't be opened." This generally indicates that the app is not verifying its receipt correctly.'

While testing in SandBox environment with v2.3.4, everything was fine and worked. Could you please help me, what could go wrong in production environment with the latest version?

Maybe I forgot of something?

### What did you expect to happen
Expected to release an update

### What happened instead
Binary was rejected due to invalid receipt verification

**Comment by tikhop** [comment]
@CineDev I'm sorry, but I can't help you here, all my apps work well with 2.3.4

**Comment by CineDev** [comment]
Maybe you could just show me the verification code in applicationDidFinishLaunching?
Mine is:
`		SwiftyStoreKit.fetchReceipt(forceRefresh: true) { result in
			switch result {
			case .success(let receiptData):
				do {
					let path = Bundle.main.url(forResource: "Items", withExtension: "list")?.path
					let receipt = try InAppReceipt(receiptData: receiptData, rootCertPath: path)
					try receipt.verify()
				}
				catch IARError.validationFailed(let reason) {
					os_log("Receipt validation failed: %s", type: .error, "\(reason)")
					exit(173)
				}
				catch IARError.initializationFailed(let reason) {
					os_log("Receipt validation failed: %s", type: .error, "\(reason)")
					exit(173)
				}
				catch {
					os_log("Receipt validation failed: %s", type: .error, error.localizedDescription)
					exit(173)
				}
			case .error(let error):
				os_log("Receipt fetching failed: %s", type: .error, error.localizedDescription)
				exit(173)
			}
		}
`
