### ISSUE TITLE
How to check purchasing status of a non consumable?

### ISSUE THREAD

**Issue by euroboy** [tikhop/TPInAppReceipt#52]
I use this function in order to get the purchasing status of a product from the local receipt:

    'func purchaseStatus(localReceipt: InAppReceipt, purchase: AppPurchase) -> PurchaseResult
    {
        let productID = purchase.productID
        switch purchase.type
        {
        case .nonConsumable:
            
            let filtered = localReceipt.purchases(ofProductIdentifier: productID)
            for purchase in filtered where purchase.productType == .nonConsumable
            {
                if purchase.cancellationDateString == nil
                {
                    return .purchaseSuccess
                }
            }
            return .notPurchased
        case .autorenewable:
            
            let filtered = localReceipt.purchases(ofProductIdentifier: productID)
            let date = Date()
            
            for purchase in filtered where purchase.isRenewableSubscription
            {
                if purchase.isActiveAutoRenewableSubscription(forDate: date)
                {
                    return .purchaseSuccess
                }
                else if let expirationDate = purchase.subscriptionExpirationDate, expirationDate < date
                {
                    return .expired
                }
            }
            return .notPurchased
        case .unknown:
            return .noValidProduct
        }
    }'

I made this logic for autorenewable subscription which seems to work. For a non-consumable I decided to check cancellationDateString if nil, but I'm not sure if this approach is correct since at the moment I'm unable to test it. Could somebody confirm if this is the right way or how it can be achieved? Thanks.

**Comment by tikhop** [comment]
Hello @euroboy,

Thanks for your question.

Your logic regarding auto-renewable subscription is completely right. However, there is no need any extra logic for checking a non-consumable purchase. If you have a non-consumable purchase inside your local receipt it means that it's valid and the user did make a purchase and it's a legit purchase. 

Moreover, based on apple docs we know that: non-consumables are a type that customers purchase once. They don't expire and can't be canceled. 

Best,
Pavel

**Comment by euroboy** [comment]
@tikhop Indeed, thank you for the help.
