### ISSUE TITLE
Swift Package Manager Apple Root Cert

### ISSUE THREAD

**Issue by Jerland2** [tikhop/TPInAppReceipt#53]
Could the apple root cert be added for Swift Package Manager?

SPM can now contain resources as of swift 5.3, Swift tools version 5.3.

Xcode 12 will allow you to do this.

**Comment by tikhop** [comment]
Yes, it will be added soon.

Thanks,
P

**Comment by Jerland2** [comment]
Sweet, thanks there is a specific WWDC Video on how to add this support (resources to packages): https://developer.apple.com/videos/play/wwdc2020/10169/

**Comment by Jerland2** [comment]
> Hi @Jerland2,
> 
> 
> 
> There is a new branch [`swift-5.3`](https://github.com/tikhop/TPInAppReceipt/tree/swift-5.3) with apple root cert included into swift pm. 

Great work!  Would be nice to also update the readme under SPM to reflect this.

**Comment by tikhop** [comment]
@Jerland2 ✅

**Comment by tikhop** [comment]
@Jerland2 I'm closing this issue. And if you are still using that branch it better to switch on `develop`. 

Best,
P
