### ISSUE TITLE
IARError.initializationFailed isn't thrown when receipt is missing

### ISSUE THREAD

**Issue by kambala-decapitator** [tikhop/TPInAppReceipt#54]
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### Environment

- [x] Sandbox
- [ ] Production

### Version
2.5

### Issue summary
IARError.initializationFailed is no longer thrown when receipt is missing, a generic Cocoa error is thrown instead. Happens in debug and Testflight builds.

I believe it's related to this change: https://github.com/tikhop/TPInAppReceipt/commit/b1a9887e8588122ffed362cb04d89fd4709c1f08#diff-5bfc68131e340d8519556c236f59bf15L44-R45

Test code:

```swift
do {
    let receipt = try InAppReceipt.localReceipt()
    try verify(receipt)
} catch IARError.initializationFailed {
    print("local receipt not found, ignoring")
} catch IARError.validationFailed(let reason) {
    print("verification error: \(reason)")
} catch {
    print("local receipt error: \(error)")
}
```

### What did you expect to happen
output:

> local receipt not found, ignoring

### What happened instead
output:

> local receipt error: Error Domain=NSCocoaErrorDomain Code=260 "Die Datei „sandboxReceipt“ konnte nicht geöffnet werden, da sie nicht existiert." UserInfo={NSURL=file:///private/var/mobile/Containers/Data/Application/6EE916DE-E05B-46C6-9757-4D250026A967/StoreKit/sandboxReceipt, NSFilePath=/private/var/mobile/Containers/Data/Application/6EE916DE-E05B-46C6-9757-4D250026A967/StoreKit/sandboxReceipt, NSUnderlyingError=0x280170090 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

**Comment by tikhop** [comment]
Hello @kambala-decapitator,

Thanks for bringing this up. I'll check it out and submit a fix shortly.

Best,
P

**Comment by tikhop** [comment]
Hi @kambala-decapitator,

Just released a new version with a fix. 

Thanks again.
