### ISSUE TITLE
Make TPInAppReceipt testable with the Xcode onboard storekit testing

### ISSUE THREAD

**Issue by chrisvanbuskirk** [tikhop/TPInAppReceipt#55]
### Issue summary
ℹ There are some differences needed when testing in Xcode.  A differing certificate must be used.

https://developer.apple.com/wwdc20/10659. About 16 minutes discusses certificates.  Testing in Xcode should be supported feature.  Thank you.

**Comment by tikhop** [comment]
Hello @chrisvanbuskirk,

I've implemented the last changes and pushed it on [`develop`](https://github.com/tikhop/TPInAppReceipt/tree/develop) branch. 
Related issue #58 is fixed as well.

I will merge these changes into `master` ~ at the end of August.

Thanks,
P
