### ISSUE TITLE
Type 'InAppReceipt' has no member 'refresh'

### ISSUE THREAD

**Issue by dobrys** [tikhop/TPInAppReceipt#63]
First, 10x for great library.
I'm trying to use it in my app, but have issue !

when i try to use :

`
InAppReceipt.refresh { (error) in
  if let err = error
  {
    print(err)
  }else{
    initializeReceipt()
  }
}
`

xcode (ver. 12) say : "Type 'InAppReceipt' has no member 'refresh'"

I installed it via pod file

please help !

**Comment by dobrys** [comment]
Found it 
pod install ver. 2.2.3 - there are no such member 
after "pod update TPInAppReceipt" - it's update to ver 3.0.0 - there are such member

**Comment by tikhop** [comment]
Hi, 

I'm glad you found it. Let me know if you have any other issues or just have some question.

Thanks,
P
