### ISSUE TITLE
background warning

### ISSUE THREAD

**Issue by dobrys** [tikhop/TPInAppReceipt#64]
sorry for disturbing, but when use "InAppReceipt.refresh { (error) in ..." 
after a while i'm got a warning from xcode 
"[BackgroundTask] Background Task 1 ("SKReceiptRefreshRequest"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this."
any suggestions ?

**Comment by tikhop** [comment]
Hi, there is nothing I can do. It comes from the system and seems that when I create `SKReceiptRefreshRequest`, system creates a background task. I just ignore this msg

**Comment by bradleyandrew** [comment]
I was getting that error as well. It seems that you may need to call the cancel() method as per the Apple Documentation:
https://developer.apple.com/documentation/storekit/skrequest

I tweaked this method in the RefreshSession Class in Extras.swift and everything seems to be working:

    func requestDidFinish(_ request: SKRequest)
    {
        requestDidFinish(with: nil)
        receiptRefreshRequest.cancel()
    }

I also added the line of code to the error method that you have implemented so the SKReceiptRefreshRequest cancels and stops running in the background when an error is flagged.

    func requestDidFinish(with error: Error?)
    {
        DispatchQueue.main.async { [weak self] in
            self?.completion?(error)
        }
        receiptRefreshRequest.cancel()
    }

Hopefully that helps someone and is correct. Thanks!

**Comment by dobrys** [comment]
10x a lot bradleyandrew

**Comment by tikhop** [comment]
@bradleyandrew thank you. I will fix it later or you can send a PR.

**Comment by tikhop** [comment]
@dobrys, @bradleyandrew i've made a pull request and going to release a new version later today. 
Thank you both.

**Comment by tikhop** [comment]
Just merged. Thanks again!

**Comment by bradleyandrew** [comment]
@tikhop Awesome work, thank you!
