### ISSUE TITLE
[Catalyst] Big Sur App Receipt not found

### ISSUE THREAD

**Issue by chrisvanbuskirk** [tikhop/TPInAppReceipt#65]
This issue is thrown in Big Sur beta 8 and validation fails

Error validating receipt: initializationFailed(reason: TPInAppReceipt.IARError.ReceiptInitializationFailureReason.appStoreReceiptNotFound)

**Comment by tikhop** [comment]
Hello Chris,

Unfortunately, I won't be able to fix the issue until Big Sur is released.

Best,
P

**Comment by chrisvanbuskirk** [comment]
@tikhop Understood Pavel.  It might now be the api but bugs in Big Sur.  The thing is really buggy still.   It doesn't see the receipt file thus the exception.

po FileManager.default.fileExists(atPath: appStoreReceiptURL!.path)
false

**Comment by tikhop** [comment]
HI @chrisvanbuskirk, 

I haven't updated to Big Sur yet, just curious whether you still have the problem.

Thanks,
P

**Comment by tikhop** [comment]
Hi @aalenliang, based on your reply on developers forum it seems that you have the same issue here. 
Am I right that `Bundle.main.appStoreReceiptURL` returns an invalid path and instead of `./../../sandboxReceipt` you get `./../../receipt`?

**Comment by chrisvanbuskirk** [comment]
@tikhop Pavel.  Sorry for the late response.  I verified everything worked in the release version.  Thanks again for your hard work.

**Comment by aalenliang** [comment]
@tikhop, Yes, but I am running an iOS app on ARM, so it is not the same case.

**Comment by chrisvanbuskirk** [comment]
I'm closing this.

**Comment by tikhop** [comment]
@chrisvanbuskirk thank you — glad it works.
