### ISSUE TITLE
"Unexpected tag. Inappropriate."

### ISSUE THREAD

**Issue by holtwick** [tikhop/TPInAppReceipt#68]
Not sure if this is a bug. On my local machine when working with Sandbox Test Users from Apple after the second start I get an error thrown. If you need the Receipt in binary form please contact me via mail at dirk.holtwick@gmail.com Thanks.

<img width="1070" alt="Holtwick-Xcode-2020-otmmUdiD@2x" src="https://user-images.githubusercontent.com/49557/97700507-3fae0b80-1aac-11eb-82d4-81abca269257.png">

<img width="402" alt="Holtwick-Xcode-2020-2IntXB1J@2x" src="https://user-images.githubusercontent.com/49557/97700436-1f7e4c80-1aac-11eb-80d3-f345ab4846da.png">

**Comment by tikhop** [comment]
Figured it out — no issue with the library itself.
