### ISSUE TITLE
Typo issue : bundleIdentifierVefirication

### ISSUE THREAD

**Issue by macoapps** [tikhop/TPInAppReceipt#69]
Hi,
thanks for your very helpful lib !
I've just noticed a small typo in ValidationFailureReason enum.
Case 'bundleIdentifierVefirication' should probably be 'bundleIdentifierVerification' ;)

EDIT : same for case 'bundleVersionVefirication'

**Comment by tikhop** [comment]
Hi,

Thank you. I'm glad you found it useful. 
I've fixed the typo and will include the fix in the next release.

Thanks again.
P
