### ISSUE TITLE
[iOS 14.2/Big Sur] activeAutoRenewableSubscriptionPurchases always empty

### ISSUE THREAD

**Issue by macoapps** [tikhop/TPInAppReceipt#70]
Hi,

I recently upgraded my iMac to Big Sur, and my iPhone to iOS 14.2.
I don't really what's wrong, but my subscriptions management doesn't work anymore. By the way, receipt.activeAutoRenewableSubscriptionPurchases is always empty, even if I have a valid renewable subscription (ie not expired). Tried on both simulator and real device, same result :(
I don't understand, because I've made no changes on this part of my app since I upgrade ...

I'm still investigating. Did some tries :

receipt.purchases.filter({ $0.isRenewableSubscription }) => returns renewable subscriptions
receipt.purchases.filter({ $0.isActiveAutoRenewableSubscription(forDate: Date()) }) => returns empty array

 Maybe some internals changes in iOS 14.2 ?

**Comment by tikhop** [comment]
Hi, 

Thanks for bringing this up. 
I will try tonight with my apps.

Best,
P

**Comment by tikhop** [comment]
Hey @macoapps,

Could you please email (tikhop (@) gmail.com) your receipt and I will try to figure it out why it doesn't work for you. 

Thanks,
P

**Comment by macoapps** [comment]
I've just sent you my receipt.
Maybe I found something :

receipt.activeAutoRenewableSubscriptionPurchases => this one is empty

receipt.purchases.filter({ $0.isRenewableSubscription }) => this one seems to contain the renewable subscriptions
Then I filter them in a loop with this test :
if let expirationDate = subscription.subscriptionExpirationDate, expirationDate > Date() {
 // do my stuff
}

Any clue ?

**Comment by tikhop** [comment]
I haven't found any issues in my projects — seems that's an issue we have discussed via email: subscription in debug mode expires in one second.

**Comment by tikhop** [comment]
Related issue: https://github.com/tikhop/TPInAppReceipt/issues/72
