### ISSUE TITLE
Fix Carthage

### ISSUE THREAD

**Issue by gubikmic** [tikhop/TPInAppReceipt#71]
When I try to add this in Xcode 11.3.1 via "Add Package Dependency…" I get an error saying "Package Resolution Failed".

> The package dependency graph can not be resolved; unable find any available tag for the following requirements:
> https://github.com/tikhop/TPInAppReceipt.git — 3.0.2..<4.0.0

Any idea how to fix this? Thanks a lot!

**Comment by gubikmic** [comment]
Update: I tried using the topmost commit and then it gives a more specific error message:

> package at 'https://github.com/tikhop/TPInAppReceipt' @ 02fb917b5488dfdc164c2b414e6d66b812726ad8 is using Swift tools version 5.3.0 but the installed version is 5.1.0

So it might just be that. I'll see if I can update and will report back

**Comment by gubikmic** [comment]
Unfortunately using Carthage doesn't work either:

> *** Skipped building TPInAppReceipt due to the error:
Dependency "TPInAppReceipt" has no shared framework schemes

**Comment by tikhop** [comment]
Hi @gubikmic,

Thanks for bringing this up. I will check Carthage. SPM works well for me.

**Comment by gubikmic** [comment]
Would be super nice if you could check Carthage. I have to stay on Mojave (and thus Xcode 11) for a little bit longer.

**Comment by tikhop** [comment]
Hi @gubikmic, 

I've tried to fix it quickly, but it's a bit more complicated then I thought. To be honest, I have never tried to used Carthage personally, but I know that it used to work well until I've changed the project structure in order to distribute it via SPM. I think, I won't fix it and probably will just discontinue Carthage support unless someone wants to fix it.

**Comment by gubikmic** [comment]
Thanks for the update. I might take a look at it or update and use SPM

**Comment by tikhop** [comment]
Yeah, better to update, but I know, how painful in might be. Another option is just to download source code and put it directly in your project.

**Comment by gubikmic** [comment]
I updated to macOS 11.1 and importing via SwiftPM works as expected.

**Comment by tikhop** [comment]
@gubikmic Glad it works for you! Let me know if you have any questions/issues/ideas.
