### ISSUE TITLE
Receipt validation doesn't work when an iOS app runs on an Arm Mac

### ISSUE THREAD

**Issue by tikhop** [tikhop/TPInAppReceipt#73]
More info: https://developer.apple.com/forums/thread/667715

**Comment by aalenliang** [comment]
Yes, it does not work. I submit my reply in the thread.

**Comment by tikhop** [comment]
Hi @aalenliang, thanks for your reply. Sounds like we just need to tweak that  conditional statement and jump straight to osx implementation like we do with catalyst apps. 
 
Unfortunately, I don’t have mac with M1 chip and I haven’t updated on Big Sur yet. So, I can’t even try to run my iOS app on macOS. I will be more than happy, If you have a chance to play with that piece of code and to try to find a proper ‘if’ statement.

Thanks,
Pavel

**Comment by tikhop** [comment]
Hi @aalenliang,

I've pushed a potential fix, would be great if you can try it out. (it's on develop branch)

https://github.com/tikhop/TPInAppReceipt/commit/1a7a1435912c56bf3ad5e1face9c542d68631abe

**Comment by aalenliang** [comment]
Hi, thanks for the quick reply! 
I tried the develop branch, unfortunately, it fails to build.

I think many API requires macOS environment but during the build process, the compiler thinks it's running in iPad.

![image](https://user-images.githubusercontent.com/20056005/101565719-9c380b00-3a08-11eb-8063-2c5ba7946287.png)

**Comment by aalenliang** [comment]
I have another project that's build for Mac, which also uses TPInAppReceipt for local receipt verification, and it works well.

So I get the macos_guid from that project since I guess the data should always be the same when running on the same mac.

Then I changed the macos_guid() method to read the data, just to see if it passes the verification, the result is still failed because the hash is not the same compares to the receipt hash.

Maybe I misunderstood, that the results of macos_guid changes when running in a different project, or we just can't use the macos_guid to verify receipt.

**Comment by tikhop** [comment]
@aalenliang Yeah, it seems that we don't have a workaround here. I've reporting it to Apple Developer Technical Support and they are checking whether it's a bug or not and what should we do.

**Comment by aalenliang** [comment]
Thanks for your work, guess we can just wait for Apple to release something.

**Comment by tikhop** [comment]
Update from apple: 

Unfortunately, they haven't provided anything helpful, and sounds like they don't know what the real issue is. We are still chatting, but they asked to write a bug report, which is, probably, waste of time, but I will do it anyway.

**Comment by tikhop** [comment]
Just got another email from apple and now they agree that it's a bug on their side and they are working on it.

**Comment by tikhop** [comment]
Well, I've got another update from Apple. Now they suggest to use the current implementation:

"_For iOS apps on M1 hardware, please use UIDevice.current.identifierForVendor for receipt validation. Thanks!_"

Maybe they have fixed it already, but I don't think so.

**Comment by aalenliang** [comment]
I'll try to verify this weekend.

**Comment by aalenliang** [comment]
It works! Local receipt verifies correctly using TPInAppReceipt installed from CocoaPods.

macOS: Version 11.1 (20C69)
Xcode: Version 12.3 (12C33)

**Comment by tikhop** [comment]
@aalenliang Great! Thanks for checking. Sounds like they have really fixed it!
