### ISSUE TITLE
Auto Renew is enable or not

### ISSUE THREAD

**Issue by HirenSensussoft007** [tikhop/TPInAppReceipt#76]
How can I get value of Auto renewable on/off from active purchases

**Comment by tikhop** [comment]
Hi @HirenSensussoft007,

All active purchases are auto renewable. 
If you want to check wether a purchase is auto renewable you can do:

```
let purchase = ... 

if purchase.isRenewableSubscription
{
    // Do something
}
```

**Comment by HirenSensussoft007** [comment]
@tikhop I think you didn't get my point 
I mean is that If the user off the auto-renewing subscription from Settings then How can I get that status in App

Please help

**Comment by tikhop** [comment]
@HirenSensussoft007 

Well, I'm not sure that user can off the auto-renewing subscription. User can cancel the auto-renewing subscription, in that case you can check whether it's canceled or not.

**Comment by HirenSensussoft007** [comment]
@tikhop Yes, It's possible to off auto-renewing(recurring) subscription from settings.
Thats why I facing issue about that how can I get recurring status of product?

**Comment by tikhop** [comment]
It’s not possible. You can either check whether a subscription is canceled or still active. If you cancel the subscription from settings then you will get an updated receipt where you can see that the subscription is canceled (not active anymore).

**Comment by HirenSensussoft007** [comment]
> It’s impossible. You can either check whether a subscription is canceled or still active. If you cancel the subscription from settings then you will get an updated receipt where you can see that the subscription is canceled (not active anymore).

No,
