### ISSUE TITLE
[Feature Request] offer_code_ref_name

### ISSUE THREAD

**Issue by plananderson** [tikhop/TPInAppReceipt#79]
Please add this: https://developer.apple.com/documentation/appstorereceipts/offer_code_ref_name

**Comment by plananderson** [comment]
UPDATE: Looks like it is not present in `receipt` 😏

**Comment by tikhop** [comment]
Hi @plananderson,

You are right - unfortunately, there is a bunch of attributes we can't access locally.

**Comment by supermnemonic** [comment]
hi @tikhop .. do you have any idea how to implement this? 

i am currious that is it possible to be implemented? if so i wanna dig deeper to your library to adjust for myself.
