### ISSUE TITLE
Using with StoreKit configuration file

### ISSUE THREAD

**Issue by ForceGT** [tikhop/TPInAppReceipt#80]
Hi I was testing In App Renewable Subscriptions using the StoreKit Configuration File
I would like to know if the receipt validation would be required in that case as I am using Revenue Cat for that and I keep getting "The receipt is not valid"
The purchase completes properly and just the receipt is not validated

**Comment by tikhop** [comment]
Hi @ForceGT,

`TPInAppReceipt` doesn't validate signature of in app receipt when you are using StoreKit Configuration File and it uses a different certificate. How Revenue Cat works in this case I don't know, but sounds it doesn't work properly. 

Related issue:
https://github.com/tikhop/TPInAppReceipt/issues/55

Here is more info:
https://developer.apple.com/wwdc20/10659

**Comment by ForceGT** [comment]
I can stop using Revenue Cat but I would like to know how I can write code for the purchases that will execute during testing as well as during the actual deployment

Any tips for that?

**Comment by tikhop** [comment]
If you just want to run different code in debug and production you can do smth like that:
```
#if DEBUG
	//Debug code
#else
	//Production code 
#endif
```

If you have any other questions related to Revenue Cat then it's better to ask here then: https://github.com/RevenueCat/purchases-ios/issues

**Comment by ForceGT** [comment]
Are you available for text on some other platform
I would like to ask some more questions

**Comment by tikhop** [comment]
Feel free to ask here on github, If you have any questions related to `TPInAppReceipt`. Otherwise, I would recommend to use `http://stackoverflow.com`
