### ISSUE TITLE
Introductory Offer Support?

### ISSUE THREAD

**Issue by Jerland2** [tikhop/TPInAppReceipt#85]
Wondering if we can get introductory offer support by implementing the ability to check eligibility?

Each product returns whether it has an introductory offer tied to it.  However in order to check eligibility we must parse the receipt. (Hence the feature request)

This would entail parsing the receipt for `is_trial_period` as well as `is_in_intro_offer_period`.  If these values are equal to 1 somewhere, a user has already used free trial/introductory offer.

Helpful articles outlining this:
https://www.revenuecat.com/blog/ios-introductory-prices
https://developer.apple.com/documentation/storekit/in-app_purchase/subscriptions_and_offers/implementing_introductory_offers_in_your_app
https://blog.apphud.com/introductory-offers-in-ios/

Helpful article snippet:

"As of iOS 12.0, SKProduct now includes subscriptionGroupIdentifier property, so it's now possible to compute Introductory Pricing eligibility locally.
While this update is great, calculating intro eligibility locally still requires a lot of unnecessary dev work.
To check intro eligibility on iOS >= 12.0, you need to: 
- Refresh the receipt so you have updated information about the user's purchases
- Parse the receipt and look for purchases made with introductory pricing
- Transform the identifiers for purchases made with intro pricing into SKProducts
- Transform the productIdentifiers you want to check eligibility for into SKProducts
- Check if there's a match - if there's at least one purchase made using intro pricing for the same product identifier or the same subscription group, the user is not eligible. If none are found, they're eligible."
https://www.revenuecat.com/blog/ios-introductory-prices

**Comment by Jerland2** [comment]
Upon closer investigation into the TPA codebase a variable similar to `promotionalOfferIdentifier` from `receipt.purchases.first` except for introductory would suffice.  as described in the article snippet.  As if we can get an identifier tied to a product signifying if the user ever used an intro price then we can compare against list of products.  If a match is found we have determined the user in ineligible.

**Comment by tikhop** [comment]
Hi @Jerland2,sorry for the late response, I've been off the grid for the last couple weeks and going to be online next week. 

I think we can do it, but I need some time. 

Thanks,
Pavel

**Comment by tikhop** [comment]
Hi @Jerland2, I'm back and about to start working on it. I think, I will have something to try later today.

**Comment by tikhop** [comment]
@Jerland2  

I've pushed two new methods to check whether user is eligible for introductory offer into `feature/introductory-offer-support` branch. 

Example:

```
...
let receipt = try InAppReceipt.localReceipt() 
var isEligible = receipt.isEligibleForIntroductoryOffer(for: "com.test.product.id")
// or 
isEligible = receipt.isEligibleForIntroductoryOffer(for: ["com.test.product.1", "com.test.product.2", "com.test.product.3"])
...
```

I think we can also add a support to check whether the user is not eligible for any products within the same subscription group.

**Comment by ungerc** [comment]
brilliant idea, we need it 🥇

**Comment by tikhop** [comment]
We will definitely have it, just need to check whether current implementation works well and if so I will merge it to master and then, I will implement checking whether the user is eligible for any products within the same subscription group.

**Comment by tikhop** [comment]
Hi @Jerland2, @ungerc

I've push code into `feature/introductory-offer-support` branch with support for checking whether user is eligible for any products within the same subscription group. 

Basically, you can retrieve a subscription group from `SKProductsResponse` using an extension provided by the library and then check whether user is eligible or not:

```

extension SKManager: SKProductsRequestDelegate 
{
    func productsRequest(_ request: SKProductsRequest, didReceive response: SKProductsResponse) 
    {
        let group = response.subscriptionGroup
        // let groups = response.subscriptionGroups // Use this if you have more than one group 
      
        let r = try InAppReceipt()
	let isEligible = r.isEligibleForIntroductoryOffer(for: group)
	
	// Do your stuff
    }
}
```

I think, I will merge it into master tomorrow.

**Comment by ungerc** [comment]
cool, I have a day off today, will check tomorrow.

**Comment by ungerc** [comment]
Hi @tikhop,  
nice - looks good

**Comment by tikhop** [comment]
@ungerc thanks for checking it out. I'm going to release it later today.

**Comment by tikhop** [comment]
Just released it.

Thanks @Jerland2 and @ungerc.

**Comment by ungerc** [comment]
thanks @tikhop, 
forgive my ignorance but is there a necessity for you to update sth in the cocoapods repo in order for the version to appear there?

**Comment by tikhop** [comment]
@ungerc I'm sorry — updating cocoapods right now.

**Comment by tikhop** [comment]
@ungerc ✅

**Comment by ungerc** [comment]
me again @tikhop 👋🏽,
this function 
`func isEligibleForIntroductoryOffer(for group: SKSubscriptionGroup) -> Bool`
seems to be duplicated? - or am I holding it wrong?
I see it's guarded by `#if canImport(StoreKit)`  and an availability check, but I do not understand it.

**Comment by ungerc** [comment]
oh and it doesn't, now I get it - my head was in a very dark place

**Comment by tikhop** [comment]
Yeah, It may seem like overengineering, but I tried to emphasize that the set of product identifiers must belong to the same subscription group.
