### ISSUE TITLE
Family sharing IAP support

### ISSUE THREAD

**Issue by gongzhang** [tikhop/TPInAppReceipt#86]
😄 Does TPInAppReceipt support reading the family sharing flag of a purchase or a subscription? This information is on the `in_app_ownership_type` property.

> When family members benefit from a shared subscription, App Store updates their receipt to include the family-shared purchase. Use the value of in_app_ownership_type to understand whether a transaction belongs to the purchaser or a family member who benefits.

https://developer.apple.com/documentation/appstorereceipts/in_app_ownership_type

**Comment by tikhop** [comment]
Hi @gongzhang, unfortunately, as I know, it’s not possible. Some fields of IAP receipt are not available in the local receipt and you can only read them using server-side receipt validation technique.

**Comment by gongzhang** [comment]
@tikhop Thanks!
