### ISSUE TITLE
CryptoSwift files need update

### ISSUE THREAD

**Issue by ungerc** [tikhop/TPInAppReceipt#87]
Hello, 
due to xcode 12.5 the CryptoSwift files that are in use here `UInt` n`+Extension.swift` are throwing errors. 
The fix is available in the CryptoSwift pod, and it is trivial.

thanks!
christian

**Comment by tikhop** [comment]
Hi @ungerc, thanks for the report. I’ll check in a couple hours.

**Comment by tikhop** [comment]
Hi @ungerc, unfortunately, I can't reproduce the issue and we are not using CryptoSwift at all.

**Comment by ungerc** [comment]
hey I installed via cocoapods 
and I see three files 
UInt16+Extension.swift
UInt32+Extension.swift
UInt64+Extension.swift
and they have a header that points to CryptoSwift

**Comment by tikhop** [comment]
Just tried to install using cocoapods and I don't see CryptoSwift and it works well.

**Comment by ungerc** [comment]
strange, if I remove the files it still builds…

**Comment by ungerc** [comment]
what am I doing wrong?

**Comment by tikhop** [comment]
Are you sure you have the last version of the pod (3.1.1)?

**Comment by tikhop** [comment]
Also, I'm not sure I have ever used CryptoSwift in the project

**Comment by ungerc** [comment]
checking now

**Comment by tikhop** [comment]
Regarding CryptoSwift, we were using it until version 3.0.0

**Comment by ungerc** [comment]
ok, so this may be an explanation

**Comment by ungerc** [comment]
`Installing TPInAppReceipt 3.1.1 (was 2.3.3)`
seems an outdated version… sorry, so I guess we  can close this issue
