### ISSUE TITLE
version 3.2.0 compilation issue (already fixed in main)

### ISSUE THREAD

**Issue by ungerc** [tikhop/TPInAppReceipt#88]
Extras.swift:162:19:
Extras.swift:225:19:
Extras.swift:236:19:

`let purchases = purchases.filter`
yields
`Pods/TPInAppReceipt/Sources/Extras.swift:236:19: variable used within its own initial value`
on our ci, probably due to an Xcode version older than 12.5/swift 5.4
this is already fixed in main
`let array = purchases.filter`

**Comment by ungerc** [comment]
@tikhop maybe I should phrase it as: would it be possible to release another version which contains these minor build fixes?
cheers, christian

**Comment by tikhop** [comment]
@ungerc should be released within a few hours.

**Comment by ungerc** [comment]
@tikhop thanks 🙏  very much appreciated

**Comment by tikhop** [comment]
@ungerc ✅

**Comment by ungerc** [comment]
🙏
