### ISSUE TITLE
Family sharing purchase not included in refreshed receipt

### ISSUE THREAD

**Issue by tealshift** [tikhop/TPInAppReceipt#91]
Hi, I have one report of a user whose spouse had purchased the same IAP they are trying to register on their phone. The purchase function returns the alert:
<img width="421" alt="Screen Shot 2021-07-16 at 11 02 30 AM" src="https://user-images.githubusercontent.com/7879237/125990170-1a5dba6f-e1e5-4918-88e4-53c50e6f7c93.png">

However the refreshed receipt does not include the product they own via family sharing.
Here is some discussion about this issue I found: https://developer.apple.com/forums/thread/684017

**Comment by tikhop** [comment]
Hi @tealshift, I'm sorry, I totally missed your issue. 

I don't know what can I do here, the library is just parsing the local receipt and it doesn't care whether the receipt is up-to-date or not.

**Comment by tealshift** [comment]
No problem. The answer provided in my link seems to do the trick.
> Calling `SKPaymentQueue.restoreCompletedTransactions` appears to generate a new receipt on the device that does now include purchases from other family members.
> You don't need to actually process any of the restored transactions, because it is just a receipt we are after, you just need to call it to get that new receipt containing items purchased by other family members.

**Comment by tealshift** [comment]
Perhaps it would be worth including this info as a tip in the ReadMe?

**Comment by tikhop** [comment]
Agree, I will include it.
