### ISSUE TITLE
Objective C example code

### ISSUE THREAD

**Issue by apatait** [tikhop/TPInAppReceipt#94]
Hi

This is not an issue per se, but I could not find a way to communicate this and I thought it'll also help others in similar boat; hence posting here.

Do you have an example of using TPInAppReceipt library in an objective C project? Sample code on how to instantiate the class and call various methods would be great. Or if you have Objective C class documentation, that'd be great too.

I am not familiar as much with Swift, and my project is in Objective C hence the request.

Thank you in advance!

**Comment by tikhop** [comment]
Hi @apatait,

Unfortunately, I don't have an example, but you can use it in objc project.

Here you can find how to install it:
https://github.com/tikhop/TPInAppReceipt/blob/master/Documentation/UseInObjCProject.md

Here is a similar question:
https://github.com/tikhop/TPInAppReceipt/issues/84 

Some old example that probably doesn't work anymore.
https://gist.github.com/tikhop/7d1215bbcea7fe8a3be3ce5ef25e15ee

Anyway, it must be pretty easy to use the library in objective c project just by checking swift examples from readme file
