### ISSUE TITLE
Some methods are not callable from Objective-C

### ISSUE THREAD

**Issue by ortekka** [tikhop/TPInAppReceipt#95]
It looks like the `InAppReceipt_Objc` wrapper class exposes only a subset of methods available in the `InAppReceipt` class.

For example, while `verify()` is available, and can be called from Objective-C in this way:

```
NSError * receiptError = nil;
if([receipt verifyAndReturnError:&receiptError])
{
    // verification successful
}
```
other methods such as `isEligibleForIntroductoryOffer()` are not exposed from the wrapper.

**Comment by tikhop** [comment]
Hi @ortekka, thanks for reporting this. I will implement all missed functionality when I have a chance. Currently, objc wrapper is in low priority and if you need something quickly you are more than welcome to make a PR.

**Comment by ortekka** [comment]
Hi Pavel,

Thanks for your reply.

I understand the ObjC wrapper is low priority for you.  In fact, I'm using TPInAppReceipt in a legacy project after successfully integrating it in a much more modern SwiftUI codebase.

Following your suggestions, I made a PR for the change I need:

	https://github.com/tikhop/TPInAppReceipt/pull/96/commits

This is my first PR ever, BTW, so please be patient if I made any rookie mistakes.

Best regards,


					-- marco

**Comment by tikhop** [comment]
Hi @ortekka,

Just merged your PR and going to release new version. Thanks for your contribution.
