### ISSUE TITLE
Clarification of Subscription Trial Period ASN.1 Field type

### ISSUE THREAD

**Issue by thaya-cameraxis** [tikhop/TPInAppReceipt#97]
Hi,

You have done a nice work. 
I want to clarify about Subscription Trial Period ASN.1 Field type.

https://developer.apple.com/library/ios/releasenotes/General/ValidateAppStoreReceipt/Chapters/ReceiptFields.html#//apple_ref/doc/uid/TP40010573-CH106-SW1

Document say's:-
If a previous subscription period in the receipt has the value “true” for either the is_trial_period or the is_in_intro_offer_period key, the user is not eligible for a free trial or introductory price within that subscription group.

Subscription Introductory Price Period :- ASN.1 Field Type 1719
Subscription Trial Period:- ASN.1 Field Type (none)

But you used "ASN.1 Field Type 1713" for Subscription Trial Period. 

Did you get "1713" from somewhere documented? or through test and Assumption?

**Comment by tikhop** [comment]
Hi @thaya-cameraxis,

Thanks for asking, unfortunately I don't remember precisely, but I assume thru extensive testing/debuging.
