### ISSUE TITLE
Build failed for iOS Simulator

### ISSUE THREAD

**Issue by ghost** [tikhop/TPInAppReceipt#99]
When building for any iOS simulator on an M1 Mac, the following error occurs: 

`Could not find module 'TPInAppReceipt' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at: /Users/wizfinger/Library/Developer/Xcode/DerivedData/appname-bkfhgmponcvrxfawozdvxtgsikwn/Build/Products/Debug-iphonesimulator/TPInAppReceipt.swiftmodule`

(TPInAppReceipt_Objc has the same result).

Build for device works correctly.

What can I do to fix this?

**Comment by tikhop** [comment]
@Wizfinger Unfortunately, I don't have m1 mac, but based on error it seems you are running x86_64 simulator (maybe rosetta is turned on). It compiles for arm64-apple which is m1, but you are asking for x86_64

**Comment by Wizfinger** [comment]
Thanks I’ll have a look here: https://stackoverflow.com/questions/56957632/could-not-find-module-for-target-x86-64-apple-ios-simulator

looks like it can be fixed by adding some settings in the podspec or the swift package manager.

**Comment by Wizfinger** [comment]
While experimenting, I have found more details:

```
TPInAppReceipt-Objc.o, building for iOS Simulator-x86_64 but attempting to link with file built for unknown-arm64
TPInAppReceipt.o, building for iOS Simulator-x86_64 but attempting to link with file built for unknown-arm64
ASN1Swift.o, building for iOS Simulator-x86_64 but attempting to link with file built for unknown-arm64
```

As per [this answer](https://stackoverflow.com/a/66233165/923288), support for arm64 Simulator slices on M1 Macs should be added in order to allow building for the Simulator.

**Comment by tikhop** [comment]
@Wizfinger I'm sorry for the delay, I've been traveling for the last two weeks and will be able to check it out in a week. If you know how to fix it — feel free to make a PR. Thank you.
